### ISSUE TITLE
Downloadable binary anywhere

### ISSUE THREAD

**Issue by mrchrisadams** [elsaland/elsa#124]
Hi there, 

Is there  downloadable binary anywhere of elsa, or do I need to compile it myself?

I can see [this step in the github actions](https://github.com/elsaland/elsa/blob/master/.github/workflows/build.yml#L51-L55) to generate and upload a binary, but it wasn't obvious to me where I might try to download a binary for linux or OS X:

```yml
   - name: Upload Elsa executables
        uses: actions/upload-artifact@v2
        with:
          name: elsa-${{ matrix.os }}
          path: ./src/github.com/elsaland/elsa/elsa-${{ matrix.os }}
```

I'm not a confident go programmer, so there might be something really obvious I'm missing, and I'm happy to update the README once I know the answer.
